version: "2"

services:
    app:
        build:
            context: ./app
        ports:
            - 8080:8080
        command: npm run start

    nginx-sample:
        build:
            context: ./nginx-sample
        image: nginx:latest
        ports:
            - 8000:80

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - 80:80
