version: "2"

services:
    app:
        build:
            context: ./app
        ports:
            - 8080:8080
        command: npm run start

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - 80:80
